### ISSUE TITLE
[FRONT-TASK] 로그아웃

### ISSUE THREAD

**Issue by joseph0926** [Selody-project/Frontend#20]
### 이슈: 로그아웃 구현

**이슈 설명:**
로그아웃 기능을 구현합니다

**체크리스트:**
- [x] 프론트에서 로그아웃 기능 구현
- [x] 백엔드 api에 맞게 로그아웃 구현

**우선순위:** 보통

**마감일:** 2023-05-27

### 링크

**Pre-requisite**: [Link to pre-req task](https://github.com/xERN-shareANDcommunity/Frontend)

**Comment by joseph0926** [comment]
로그아웃을 트리거할 로그아웃 버튼이 현재 없는거같습니다
이에 대한 의견 주시면 감사하겠습니다!

혹시 제가 못찾은거면 어디있는지 알려주실수있으실까요??

**Comment by uiseop** [comment]
> 로그아웃을 트리거할 로그아웃 버튼이 현재 없는거같습니다 이에 대한 의견 주시면 감사하겠습니다!
> 
> 혹시 제가 못찾은거면 어디있는지 알려주실수있으실까요??

<img width="693" alt="image" src="https://github.com/Selody-project/Frontend/assets/75655047/679f9806-7d09-4609-b3f7-6c3d8fff6834">

피그마 - 기획 상세에 로그아웃 버튼 있는듯합니다!

**Comment by 97970z** [comment]
> 로그아웃을 트리거할 로그아웃 버튼이 현재 없는거같습니다 이에 대한 의견 주시면 감사하겠습니다!
> 
> 혹시 제가 못찾은거면 어디있는지 알려주실수있으실까요??

저번에 로그아웃을 마이페이지에 넣을지 헤더에 넣을지 의논하다가
헤더에 넣기로 했었던거 같습니다. 지금 코드상에서는 작업이 안되어있습니다.

**Comment by uiseop** [comment]
> > 로그아웃을 트리거할 로그아웃 버튼이 현재 없는거같습니다 이에 대한 의견 주시면 감사하겠습니다!
> > 혹시 제가 못찾은거면 어디있는지 알려주실수있으실까요??
> 
> <img alt="image" width="693" src="https://user-images.githubusercontent.com/75655047/240108017-679f9806-7d09-4609-b3f7-6c3d8fff6834.png">
> 피그마 - 기획 상세에 로그아웃 버튼 있는듯합니다!

앗.. ㅎ😂 디자인 페이지에서 말씀하신게 아니셨군요

**Comment by joseph0926** [comment]
> > 로그아웃을 트리거할 로그아웃 버튼이 현재 없는거같습니다 이에 대한 의견 주시면 감사하겠습니다!
> > 
> > 혹시 제가 못찾은거면 어디있는지 알려주실수있으실까요??
> 
> 저번에 로그아웃을 마이페이지에 넣을지 헤더에 넣을지 의논하다가
> 헤더에 넣기로 했었던거 같습니다. 지금 코드상에서는 작업이 안되어있습니다.

아하 넵넵 그러면 제가 일단 헤더 컴포넌트에 추가해놓겠습니다~
