### ISSUE TITLE
[FRONT-TASK] 반복 일정 관련 논의 사항

### ISSUE THREAD

**Issue by Taehoya** [Selody-project/Frontend#22]
# Description
유저 일정 조회 기능을 개발하던 중에 해당 부분에 어려움이 있어 의견을 구하고자 이슈 남깁니다!

### 우선 아래의 내용을 확실하게 짚고 넘어가겠습니다.
* 초기 기획에서는 반복 일정에 대한 옵션으로 `Year`, `Month`, `Week`, `Day`를 제공하고 있습니다.
* `startDate`, `endDate` 값은 각각 개별 일정이 언제 시작해서 언제 끝나는지를 나타내고 있습니다.

### 문제 상황 설정
*  `2022-05-05 12:00:00` ~ `2022-05-05 14:00:00` 구간에 `중요한 연례 행사`라는 `연간 반복 일정`이 있다.
* 오늘은 위 일자의 1년 뒤인 `2023-05-05` 이다
* 서버는 `2022-05-05`에 존재하였던  `중요한 연례 행사` 일정을, 1년이 지난 `2023-05-05`에도 동일하게 오늘의 일정으로 판별할 수 있어야 한다.

### 문제점
현재 저희는 `startDate`와 `endDate`만을 체크해서 해당 일정이 특정 구간에 속하고 있는가를 체크하는 방식으로 GET 요청을 처리하도록 구현하고 있었습니다. 하지만 위와 같은 상황에서, 기존의 방식( `startDate`와 `endDate`만으로 일정을 구분)만을 통해서는 모든 일정을 완벽하게 판별해 낼 수가 없었습니다. 이러한 반복 일정들을 처리하기 위해서는 추가적으로 아래와 같은 과정이 필요하게 됩니다.

* 연 단위의 반복 일정이라면 해당 일정의 `month`, `day`값을 확인하여 현재의 일자와 비교
* 월 단위의 반복 일정이라면 해당 일정의 `day`값을 확인하여 현재의 일자와 비교
* 주 단위의 반복 일정이라면 해당 일정이 `무슨 요일`인지를 확인하여 현재 요일과 비교
* 일 단위의 반복 일정이라면 해당 일정은 그냥 오늘의 일정

위와 같이 여러 방법을 사용해서 판별해야만 모든 반복 일정을 처리할 수가 있게 됩니다. 
(다른 방법이 있을 수도 있겠습니다. 이 부분에 대한 의견이 있으시면 편하게 말씀해주세요.)

불가능한 로직은 아닙니다. 
하지만 여러 사용자가 동시에 이러한 요청을 보낸다면, 아마 기능적으로 문제가 생기지 않을까 생각합니다.

### 개선 방안
로직의 복잡도를 개선하기 위해 반복 일정의 간소화에 대해 어떻게 생각하시는지 여쭙고 싶습니다.
* 기존에 제공하던 4가지의 옵션대신, `Week`, `Day` 2가지의 옵션만을 제공 
![KakaoTalk_20230507_203017387](https://user-images.githubusercontent.com/81506668/236680976-6ca69fb5-fbe5-46f9-bed3-8f7687878d85.png)
( 위 사진은 구글 캘린더를 캡쳐한 것입니다. )

* 월~일 모든 요일을 선택하여 `매일 반복되는 일정`을 처리할 수 있습니다. 
* 특정 요일만을 골라 `주 단위로 반복되는 일정`을 처리할 수 있습니다.

결과적으로 위와 같이 개선할 경우, 따로 `month`, `day` 값을 검사할 필요가 없어지게 됩니다.
특정 반복 일정이 `어느 요일에 반복되고 있는지만 확인`을 하면, 그 일정이 오늘의 일정인지를 판단할 수 있게 됩니다. 
(만약 반복 종료 시점을 정할 수 있도록 한다면, 종료 시점을 확인하는 과정도 추가되겠지만요.)

사용자 편의성 면에서는 당연히 4가지의 옵션을 모두 제공하는 것이 더 좋겠지만, 구현에 어려움이 있어 다른 분들의 생각은 어떠신지 의견을 구해봅니다.

**Comment by joseph0926** [comment]
말씀해주신 개선방안으로 진행해주셔도 괜찮을거같습니다

**Comment by 97970z** [comment]
저도 괜찮은 것 같습니다~

**Comment by GGANCC1** [comment]
그럼 우선 위 방식대로 구현을 해보겠습니다. 토요일에 다 같이 이야기 해보고 확정을 지은 뒤, 수정을 하거나 해서 PR올리도록 할게요. 그때까지는 ISSUE7 브렌치에 업데이트해놓도록 하겠습니다.
