### ISSUE TITLE
[BUG] 쿠키(httpOnly)를 이용했을 때 인증 여부 확인

### ISSUE THREAD

**Issue by joseph0926** [Selody-project/Frontend#38]
### 설명

**상황:**
백엔드에서 토큰을 전달 방식을 쿠키로 설정
이때 XSS(Cross-Site Scripting) 공격으로부터 보호를 위해 httpOnly를 사용 (즉, 프론트에서 쿠키 컨트롤 불가능)
하지만 프론트에서 유저가 쿠키를 보유..즉, 인증된 유저인지 확인할 방법이 필요함

**시도:**
1. 백엔드에서 헤더에 포함되어있는 쿠키가 유효한지 판단하는 GET 라우터(또는 미들웨어)를 하나 정의하여, 유효하다면 유저정보를 반환해줌 / 이를 프론트에서는 루트 레벨 컴포넌트(해당 프로젝트 기준 App.jsx 또는 Root.jsx)에서 지속적으로 요청
```javascript
// App.jsx
const dispatchFn = useDispatch();

	useEffect(() => {
		dispatchFn(getCurrentUser());
	}, [dispatchFn]);

// Root.jsx
useEffect(() => {
		if (user) {
			navigate("/");
		}
	}, [user, navigate]);
```
해결방법 1에 대한 결과:
최초 로그인시에는 정상적으로 작동하지만 이후 새로고침등 페이지 이동시 여전히 문제 존재

2. PrivateRoute 컴포넌트 생성
PrivateRoute 컴포넌트를 만들어서 보호된 라우트에 대한 접근을 제한
```javascript
// PrivateRoute.jsx
const PrivateRoute = ({ children }) => {
  const user = useSelector((state) => state.user.user);
  const userLoading = useSelector((state) => state.user.userLoading);
  const dispatchFn = useDispatch();
  const location = useLocation();

  useEffect(() => {
    if (!user && !userLoading) {
      dispatchFn(getCurrentUser());
    }
  }, [user, userLoading, dispatchFn]);

  if (userLoading) {
    return <div>Loading...</div>;
  }

  if (!user) {
    return <Navigate to="/login" state={{ from: location }} />;
  }

  return children;
};

export default PrivateRoute;

// App.jsx
const router = createBrowserRouter([
  {
    path: "/",
    element: <Root />,
    errorElement: <ErrorPage />,
    children: [
      { 
        index: true,
        element: (
          <PrivateRoute>
            <PersonalSchedulePage />
          </PrivateRoute>
        )
      },
    ],
  },
  { path: "/landing", element: <LandingPage /> },
  { path: "/login", element: <LoginPage /> },
  { path: "/signup", element: <SignUpPage /> },
]);

```
해결방법2에 대한 결과 :
여전히 동일한 문제 발생

**Comment by uiseop** [comment]
CORS - Credential 문제로 보여요~ 한 번 확인해보시겠어요?

**Comment by joseph0926** [comment]
> CORS - Credential 문제로 보여요~ 한 번 확인해보시겠어요?

음,, CORS는 엔드포인트를 설정해놔서 해결했구(vite config 파일), Credential 설정 안해서 헤더에 쿠키 안담기는 문제는 user-slice 맨위에 보시면 axios config에 설정해놨습니다!!

**Comment by uiseop** [comment]
> > CORS - Credential 문제로 보여요~ 한 번 확인해보시겠어요?
> 
> 음,, CORS는 엔드포인트를 설정해놔서 해결했구(vite config 파일), Credential 설정 안해서 헤더에 쿠키 안담기는 문제는 user-slice 맨위에 보시면 axios config에 설정해놨습니다!!

그렇네요..! 최초 로그인 후에 새로고침 않고 다른 요청에는 토큰값이 정상적으로 전달될까요?

**Comment by joseph0926** [comment]
> > > CORS - Credential 문제로 보여요~ 한 번 확인해보시겠어요?
> > 
> > 
> > 음,, CORS는 엔드포인트를 설정해놔서 해결했구(vite config 파일), Credential 설정 안해서 헤더에 쿠키 안담기는 문제는 user-slice 맨위에 보시면 axios config에 설정해놨습니다!!
> 
> 그렇네요..! 최초 로그인 후에 새로고침 않고 다른 요청에는 토큰값이 정상적으로 전달될까요?

음 현재 상태를 조금 자세히 말씀드리면


문제 상황:

페이지를 이동할 때마다 쿠키의 유효성을 확인해야 하는 문제를 해결하기 위해서,

쿠키의 유효성을 확인하고 GET 라우터를 사용하여 사용자 정보를 반환합니다

정의한 후 라우터에 지속적인 요청을 전송하여 해결되었습니다.

따라서 로컬 스토리지를 사용하지 않고 httpOnly의 이점을 활용할 수 있었습니다

또한 해당 방법을 적용함으로 인해 JavaScript 액세스(XSS 공격) 보호 상태를 유지하면서, 페이지를 전환하거나 다시 로드할 때도 인증 상태를 유지할 수 있었습니다.



그렇지만

createAsyncThunk를 활용하여 인증 관련 로딩 상태를 관리하고있는데,

데이터가 도착한 후에만 인증 정보를 확인하고 싶지만, 현재는 데이터 도착전에 useEffect에 의해서 먼저 인증 정보를 확인해버려서 null이 반환됩니다 ㅜㅜ


[code link](https://joseph0926.notion.site/Managing-the-status-of-async-operations-when-using-the-redux-toolkit-2c4d70354fa544b1b1efd14a122c533d)

**Comment by joseph0926** [comment]
뭔가 비동기 관련 로딩 상태를 적절하게 컨트롤하면될거같은데,,, 쉽지않네요

**Comment by uiseop** [comment]
사전에 router에서 `path: /*`로 받아서 이 부분에서 인증 정보를 처리한 뒤에 완료되면 다른 페이지 컴포넌트로 link 시켜주는 방식은 어떨까요?

**Comment by joseph0926** [comment]
> 사전에 router에서 `path: /*`로 받아서 이 부분에서 인증 정보를 처리한 뒤에 완료되면 다른 페이지 컴포넌트로 link 시켜주는 방식은 어떨까요?

오 좋은 방법같아요! 한번 적용해보고 결과 말씀드리겠습니다~!

**Comment by uiseop** [comment]
> > 사전에 router에서 `path: /*`로 받아서 이 부분에서 인증 정보를 처리한 뒤에 완료되면 다른 페이지 컴포넌트로 link 시켜주는 방식은 어떨까요?
> 
> 오 좋은 방법같아요! 한번 적용해보고 결과 말씀드리겠습니다~!

LocalStorage 말고 Cookie를 사용해서 토큰값을 저장하시는 이유가 있으실까요?

**Comment by joseph0926** [comment]
> <del>사전에 router에서 `path: /*`로 받아서 이 부분에서 인증 정보를 처리한 뒤에 완료되면 다른 페이지 컴포넌트로 link 시켜주는 방식은 어떨까요?</del>
> 
> 유저 인증 정보랑 본 요청이랑 분리하는 이유가 있을까요? 한 번에 진행하고 서버에서 클라이언트가 보내온 요청에 유효하지 않은 토큰값이 들어있으면 `reject` 결과를 내보내는건 어떨까요??

유저 인증 정보를 저장할 방법이 없어서 해당 요청을 지속적으로 보내는 방법을 채택하였습니다!

**Comment by uiseop** [comment]
> > ~사전에 router에서 `path: /*`로 받아서 이 부분에서 인증 정보를 처리한 뒤에 완료되면 다른 페이지 컴포넌트로 link 시켜주는 방식은 어떨까요?~
> > 유저 인증 정보랑 본 요청이랑 분리하는 이유가 있을까요? 한 번에 진행하고 서버에서 클라이언트가 보내온 요청에 유효하지 않은 토큰값이 들어있으면 `reject` 결과를 내보내는건 어떨까요??
> 
> 유저 인증 정보를 저장할 방법이 없어서 해당 요청을 지속적으로 보내는 방법을 채택하였습니다!

유저 인증 정보가 토큰값 아닌가요?

**Comment by joseph0926** [comment]
> > > 사전에 router에서 `path: /*`로 받아서 이 부분에서 인증 정보를 처리한 뒤에 완료되면 다른 페이지 컴포넌트로 link 시켜주는 방식은 어떨까요?
> > 
> > 오 좋은 방법같아요! 한번 적용해보고 결과 말씀드리겠습니다~!
> 
> LocalStorage 말고 Cookie를 사용해서 토큰값을 저장하시는 이유가 있으실까요?

코멘트 상세설명에도 언급했지만,
xss 공격을 고려하여 토큰 인증 방식중 httponly 쿠키 방식을 선택하였습니다!
또한 세션방식과 토큰방식중 토큰방식을 선택한 이유는 초기 백엔드분들과 회의를 통해 정하였습니다~!
로컬스토리지 사용을 피하는것은 사용시 httponly 쿠키 사용 의미가 없어지기 때문입니다!

**Comment by uiseop** [comment]
> > > > 사전에 router에서 `path: /*`로 받아서 이 부분에서 인증 정보를 처리한 뒤에 완료되면 다른 페이지 컴포넌트로 link 시켜주는 방식은 어떨까요?
> > > 
> > > 
> > > 오 좋은 방법같아요! 한번 적용해보고 결과 말씀드리겠습니다~!
> > 
> > 
> > LocalStorage 말고 Cookie를 사용해서 토큰값을 저장하시는 이유가 있으실까요?
> 
> 코멘트 상세설명에도 언급했지만, xss 공격을 고려하여 토큰 인증 방식중 httponly 쿠키 방식을 선택하였습니다! 또한 세션방식과 토큰방식중 토큰방식을 선택한 이유는 초기 백엔드분들과 회의를 통해 정하였습니다~! 로컬스토리지 사용을 피하는것은 사용시 httponly 쿠키 사용 의미가 없어지기 때문입니다!
> 
> 음,, 인증 정보가 토큰인건 맞지만, 프론트에서 직접 컨트롤 할수가없어 해당 방법을 고려하게되었습니다 혹시 제가 말씀하신것을 잘못이해하고있다면 추가적으로 말씀해주세요!

그렇죠. `httpOnly` 속성을 사용하면 Javascsript로 해당 쿠키에 접근할 수 없어서 보안적으로 향상되는 것으로 알고 있습니다. 다만 CSRF 공격으로부터 완전히 보호되지 않는다는 문제점도 있겠네요. JWT는 서버에서 유저 로그인 정보를 세션처럼 저장하지 않기 때문에 만약 해당 토큰값이 노출되게 된다면 어떻게 처리해야할까요?? 서버에서 지울 수 있는 방법도 없는데 말이죠

JWT토큰을 사용하는 시점에서 보안적인 부분을 얼마만큼 생각해야할까?를 생각해보자면 유효시간을 설정하는 부분이 있을 것 같네요. 보안적으로 중요한 서비스의 경우 유효시간을 짧게 해서 해당 지속적으로 토큰을 요구하는 방식이 사용될 수 있겠지만, 보안적으로 그렇게 중요하지 않은 서비스라면 클라이언트단에서 어느정도는 유지/관리 할 수 있도록 `httpOnly` 속성을 사용하기 보다는 해당 값 자체를 상태 관리 라이브러리를 사용해서 관리할 수 있으면 이전처럼 `1. 인증 요청 -> 2. 본 요청`의 두 번의 프로세스에서 바로 `본 요청`으로 하나의 프로세스로 줄일 수 있겠다는 생각이 드네요.

또한, 쿠키를 제공한 서버로의 요청에는 해당 서버가 제공했던 쿠키 데이터가 어떤 요청에 있든 모두 함께 포함돼서 전송되는 특성이 있고, 저장 용량의 한계 같은 특징도 있어서 저희가 구현하고자 하는 서비스에서는 `httpOnly` 속성이 꼭 필요할까 라는 생각이 듭니다.

**Comment by joseph0926** [comment]
> > > > > 사전에 router에서 `path: /*`로 받아서 이 부분에서 인증 정보를 처리한 뒤에 완료되면 다른 페이지 컴포넌트로 link 시켜주는 방식은 어떨까요?
> > > > 
> > > > 
> > > > 오 좋은 방법같아요! 한번 적용해보고 결과 말씀드리겠습니다~!
> > > 
> > > 
> > > LocalStorage 말고 Cookie를 사용해서 토큰값을 저장하시는 이유가 있으실까요?
> > 
> > 코멘트 상세설명에도 언급했지만, xss 공격을 고려하여 토큰 인증 방식중 httponly 쿠키 방식을 선택하였습니다! 또한 세션방식과 토큰방식중 토큰방식을 선택한 이유는 초기 백엔드분들과 회의를 통해 정하였습니다~! 로컬스토리지 사용을 피하는것은 사용시 httponly 쿠키 사용 의미가 없어지기 때문입니다!
> > 
> > 음,, 인증 정보가 토큰인건 맞지만, 프론트에서 직접 컨트롤 할수가없어 해당 방법을 고려하게되었습니다 혹시 제가 말씀하신것을 잘못이해하고있다면 추가적으로 말씀해주세요!
> 
> 그렇죠. `httpOnly` 속성을 사용하면 Javascsript로 해당 쿠키에 접근할 수 없어서 보안적으로 향상되는 것으로 알고 있습니다. 다만 CSRF 공격으로부터 완전히 보호되지 않는다는 문제점도 있겠네요. JWT는 서버에서 유저 로그인 정보를 세션처럼 저장하지 않기 때문에 만약 해당 토큰값이 노출되게 된다면 어떻게 처리해야할까요?? 서버에서 지울 수 있는 방법도 없는데 말이죠
> 
> JWT토큰을 사용하는 시점에서 보안적인 부분을 얼마만큼 생각해야할까?를 생각해보자면 유효시간을 설정하는 부분이 있을 것 같네요. 보안적으로 중요한 서비스의 경우 유효시간을 짧게 해서 해당 지속적으로 토큰을 요구하는 방식이 사용될 수 있겠지만, 보안적으로 그렇게 중요하지 않은 서비스라면 클라이언트단에서 어느정도는 유지/관리 할 수 있도록 `httpOnly` 속성을 사용하기 보다는 해당 값 자체를 상태 관리 라이브러리를 사용해서 관리할 수 있으면 이전처럼 `1. 인증 요청 -> 2. 본 요청`의 두 번의 프로세스에서 바로 `본 요청`으로 하나의 프로세스로 줄일 수 있겠다는 생각이 드네요.
> 
> 또한, 쿠키를 제공한 서버로의 요청에는 해당 서버가 제공했던 쿠키 데이터가 어떤 요청에 있든 모두 함께 포함돼서 전송되는 특성이 있고, 저장 용량의 한계 같은 특징도 있어서 저희가 구현하고자 하는 서비스에서는 `httpOnly` 속성이 꼭 필요할까 라는 생각이 듭니다.

아하 그런 말씀이시군요!
제가 잘못이해했네요 죄송합니다,,
말씀해주신대로 꼭 필요하진 않을거같습니다!

다만 백엔드에 그렇게 설정되어있어서 최대한 백엔드에 맞게 처리해보려고 시도한것이였습니다!

음.. 이부분은 오늘 회의에서 자세히 다뤄봐도 괜찮을거같아요
말씀해준대로 httponly를 고집할 특별한 이유가 없으니 다른 방식을 채택하는것도 고려하여서, 결정되면 백엔드분들에게 말씀드리는 방향으로 회의를 진행하면 좋을거같습니다:)

좋은 의견 감사합니다!

**Comment by GGANCC1** [comment]
근데 제가 사실 이전부터 잘 이해가 안되었던 부분인데, 인증된 유저인 것을 따로 확인하는 요청을 서버측에 보낼 필요가 있을까요?  이 부분이 잘 이해가 안되어서, 음...어떤 맥락에서 해당 기능이 필요한 것인지 한 번만 설명 부탁드립니다ㅠㅠ.

왜냐하면 지금 서버에서는 어차피 모든 유저에게 공통적으로 보이는 정적인 페이지가 아닌 이상은, 모든 요청에서 쿠키를 열어서 jwt를 검증하는 과정을 거치고 있거든요. 또 그 과정에서 토큰이 위조되었거나 유효하지 않은 경우에는 따로 401 권한 없음 code를 response하고 있구요. 만약 프론트 측에서 백엔드 서버에 요청을 보냈을 때, 401 code를 리턴값으로 받게된다면, 이게 곧 인증된 유저가 아님을 뜻하는게 아닌지...
만약 토큰에 저장된 정보 자체가 필요하신 거라면, 따로 get request를 통해 유저 정보를 얻어올 수 있도록 하는 게 더 낫지 않을까 싶습니다.

**Comment by GGANCC1** [comment]
우선 답변 감사합니다. 
1. 혹시 페이지 이동에 관한 예시를 조금만 자세히 알려주실 수 있을까요?
어떤 페이지에서 어떤 페이지로 넘어가는데에 어떤 요청이 있고, 어떤 값이 필요한지...등등
정확히 어떤 상황에서 문제가 발생하는 건지 궁금합니다! 
사실 그냥 httponly 옵션을 지우면 간단하긴 한데, 아무래도 정석적인 아닌 것 같아서요. 
검색을 해도 그렇다할 래퍼런스가 안나와서 이렇게 질문 드립니다! 같이 고민해보고 싶습니다.

2. 페이지 이동이나 새로고침 등의 작업이 있을 때, 페이지를 다시 띄워줄려면, 어차피 매번 서버측으로 get api 요청을 보내게 되지 않나요? 그렇지 않은 경우가 있는건지 궁금합니다. 이 부분이 제가 좀 헷갈려서요.

3. 백엔드 서버로 요청을 보낼때 순서가 어떻게 되나요?  get api/auth/token/verify로 인증된 유저인지를 확인  -> ( 인증된 유저라면 필요한 request를 요청) 이렇게 두 단계로 이루어지는 게 맞을까요?

**Comment by joseph0926** [comment]
> 우선 답변 감사합니다.
> 
> 1. 혹시 문제 상황에서의 페이지 이동에 관한 예시를 조금만 자세히 알려주실 수 있을까요?
>    어떤 페이지에서 어떤 페이지로 넘어가는데에 어떤 요청이 있고, 어떤 값이 필요한데 유효한 인증인지를 검사할 필요가 있다...등등
>    정확히 어떤 상황에서 문제가 발생하는 건지 궁금합니다!
>    사실 그냥 httponly 옵션을 지우면 간단하긴 한데, 아무래도 정석적인 해결방안은 아닌 것 같아서요.
>    검색을 해도 그렇다할 래퍼런스가 안나와서 이렇게 질문 드립니다! 같이 고민해보고 싶습니다.

일단 클라이언트측에는 크게 두 부분으로 나뉘어져있습니다
1. 인증이 필요한 페이지들 / 2. 인증이 필요없는 페이지들
1번 예시 -> LandingPage, SignPage,
2번 예시 -> 이외페이지
따라서 로그인 이후부터는 모든 페이지 이동에서 인증 여부를 알아야합니다
(ex, if (!user) {navigate("/landing"}}
하지만 현재 로컬스토리지등을 사용하지 않으므로 사용자 로컬에 인증정보(user객체)를 저장할 방법이 없습니다
그러므로 페이지 이동마다 user객체에 값을 채워넣기위해 GET 요청을 보내어 새롭게 채워넣습니다
(ex, const response = await fetch(~~~) .... const data = response.data .... builder.fulfild(state.user = payload(백엔드로부터 받은 데이터))
(예시코드들은 정확하지 않을 수 있습니다 참고만 해주세요)

> 2. 페이지 이동이나 새로고침 등의 작업이 있을 때, 페이지를 다시 띄워줄려면, 어차피 매번 서버측으로 get api 요청을 보내게 되지 않나요? 그렇지 않은 경우가 있는건지 궁금합니다. 이 부분이 제가 좀 헷갈려서요.

저희는 페이지 생성에 SSG나 SSR이 아닌 CSR을 사용하므로 페이지 생성을 위한 서버에 GET요청은 특별히 없습니다
이부분은 제가 질문을 잘못이해하고 답변한것일수도있으니, 만약 그렇다면 말씀해주세요

> 3. 현재 백엔드 서버로 요청을 보낼때 순서가 어떻게 되나요?  get api/auth/token/verify로 인증된 유저인지를 확인  -> ( 인증된 유저라면 필요한 request를 요청) 이렇게 두 단계로 이루어지는 게 맞을까요?

로그인 이후부터는 서버에 대한 모든 요청에 앞서서 get api/auth/token/verify 이 필요합니다

**Comment by joseph0926** [comment]
> 아 이해했습니다. 감사합니다. 근데 해당 방안이 현재 문제를 해결할 수 있을지 잘 모르겠습니다. 어차피 토큰을 열어볼 수 있더라도, 토큰의 payload에는 nickname 정보밖에는 담고 있지 않거든요. 그럴수밖에 없기도 하고요. 아마 httponly를 지우더라도, 로컬 스토리지를 사용하지 않은 채로 nickname외의 정보를 사용하려면 서버측에 요청을 따로 한 번 더 보내야하기는 할겁니다.
> 
> 그냥 api/auth/token/verify대신에 api/user/profile이라는 GET 요청을 통해 유저 정보를 받아올 수 있도록 하면 되지 않을까요? 뭐 사실 그냥 엔드포인트만 다르고 지금과 기능은 동일하긴 합니다.
> 
> 일단 제가 매커니즘은 아래와 같습니다.
> 
> 1. GET api/user/profile 요청을 보냄
> 
> * 유효한 쿠키(토큰)이 아닐 시, 401 status 값을 반환 받게됨. 401 값을 반환 받으면 로그인 페이지로 리다이렉트.
> * 유효한 쿠키(토큰)이라면, 유저 정보를 그대로 반환 받게 됨. 그럼 그냥 해당 정보를 user 객체에 채워넣음.
> 
> 2. 위에서 user 객체를 채워 넣었다면, 이제 필요한 요청을 보낼 수 있게됨.
> 
> 또, 로컬 또는 세션 스토리지를 사용하되, 해당 데이터를 암호화하여 저장하는 방식에 대해서는 어떻게 생각하시나요?

넵 로컬스토리지 사용은 아무래도 해야할거같습니다
또한 암호화에 대해선 저도 동의하며, 혹시 몰라 코드도 작성해두었습니다
의견 감사합니다!!!

**Comment by joseph0926** [comment]
해결한거같습니다

backend 폴더에서 controller/user.js에서
async function getUserInfo(req, res, next) {
  const { nickname } = req.body.nickname;
  try {
    const exUser = await User.findOne({
      where: { nickname },
    });
    return res.status(200).json({ exUser });
  } catch (err) {
    return next(err);
  }
}
로 고쳐주세요

middleware/apiError.js 에서
const apiError = (error, req, res, next) => {
  res.status(402).json({ error: error.message });
};
module.exports = apiError;
로 고쳐주세요

프론트는 bug-인증여부확인 브렌치를 적용해주세요

**Comment by joseph0926** [comment]
> 해결한거같습니다
> 
> backend 폴더에서 controller/user.js에서 async function getUserInfo(req, res, next) { const { nickname } = req.body.nickname; try { const exUser = await User.findOne({ where: { nickname }, }); return res.status(200).json({ exUser }); } catch (err) { return next(err); } } 로 고쳐주세요
> 
> 프론트는 bug-인증여부확인 브렌치를 적용해주세요

- 요약
프론트에서 비동기 처리 또는 로딩 상태 문제로 인한 로직 순서 문제로 인해 인증정보가 undefined를 반환했던것이 아닌,
그냥 db에서 nickname: {nickname: "test"} 이런식으로 되어서 실제로 해당 유저를 못찾아서 undefined를 반환했던거였습니다
