### ISSUE TITLE
[FRONT-TASK] schedule 조회 관련 개선점

### ISSUE THREAD

**Issue by GGANCC1** [Selody-project/Frontend#44]
# Description
* `GET api/user/calendar?date=` 
* `GET api/user/calendar/todo?date=`
* 기존 방식의 문제 상황을 고려하여, 조회 기능 사용 시 통신 규칙을 수정하는 게 좋을 것 같습니다.
--------------
### 현재 상황
* `GET api/user/calendar?date=` 호출 시에는 `서버 기준(UTC timezone)`의 `한달` 일정을 response
* `GET api/user/calendar/todo?date=` 호출 시에는 `서버 기준(UTC timezone)`의 `하루` 일정을 response
* 서버에서는 모든 데이터를 `UTC timezone`으로 저장 및 관리
--------------
### 문제점
* **특정 구간의 일정 조회 시, local timezone을 고려하지 않은 채로 일정을 조회하고 있음.**

예를들어 `대한민국`에 거주하고 있는 사용자가 `4월 일정`을 조회하고자 한다면, 서버 시간대인 `UTC timezone` 환경에서는 
`2023-03-31 T15:00:00.000Z ~ 2023-04-30 T14:59:59.999Z` 구간의 일정을 조회할 수 있도록 구현되어야 함

* 하지만 현재는 단순히 서버 timezone만을 고려하여 `2023-04-01 T00:00:00.000Z ~ 2023-04-30 T23:59:59.999Z`의 일정만을 조회.
* **사용자에게 알맞은 한달(하루) 일정을 넘겨주기 위해서는 각 사용자의 local timezone을 고려해야만 함**
* **하지만 백엔드 서버측에서는 각 사용자의 timezone을 알 수 있는 방법이 없음**
--------------
### 개선 방안
* `client 측에서 일정 조회를 request할 때에 UTC timezone에서의 원하는 시간대를 직접 지정`하여 보내주면 어떨까 합니다.
* 위의 예시에서는 `2023-04-01 T00:00:00.000+09:00 ~ 2023-04-30 T23:59:59.999+09:00`의 구간을 
`{ startDateTime: "2023-03-31 T15:00:00.000Z", endDateTime: "2023-04-30 T14:59:59.999Z" }`와 같이 변환하여 보내게 됩니다.
--------------
### 기대 효과 
* 각 사용자의 시간대에 맞는 일정을 올바르게 조회할 수 있게 됩니다.
* 한달, 하루 이외에도 다른 구간을 임의로 지정하여 일정을 조회할 수 있기 때문에, 일정 조회 기능을 유연하게 사용할 수 있게 됩니다.
* 구간 데이터를 직접 입력받게 된다면 백엔드 서버측에서는 위의 두 api를 하나로 통합할 수 있게 됩니다.
* 한달 일정 조회와 하루 일정 조회는 같은 로직을 사용하고 있으므로, 이를 하나로 통합하면 중복되는 코드를 많이 줄일 수 있습니다.

**Comment by joseph0926** [comment]
client 측에서 일정 조회를 request할 때에 UTC timezone에서의 원하는 시간대를 직접 지정하여 보내주면 어떨까 합니다.

이부분을 담담하는 로직을 따로 짜면 될거같네요!

**Comment by GGANCC1** [comment]
> client 측에서 일정 조회를 request할 때에 UTC timezone에서의 원하는 시간대를 직접 지정하여 보내주면 어떨까 합니다.
> 
> 이부분을 담담하는 로직을 따로 짜면 될거같네요!

네 맞습니다!
